CAPITAL = 1
CUSTEIO = 2
BOLSAS_PRAE = 3

FINALIDADE_IDR_CUSTEIO = 40
FINALIDADE_IDR_CAPITAL = 41
FINALIDADE_TRANFERENCIA_CAPITAL = 100
FINALIDADE_TRANSFERENCIA_CUSTEIO = 1001

TRANSFERENCIA_FINALIDADES = [FINALIDADE_IDR_CUSTEIO, FINALIDADE_IDR_CAPITAL, FINALIDADE_TRANFERENCIA_CAPITAL,
                             FINALIDADE_TRANSFERENCIA_CUSTEIO]
