"""
Django settings for ngo_ccsh project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import json
import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()  # carrega variáveis de ambiente do arquivo .env, se existir

BASE_DIR = Path(__file__).resolve().parent.parent

SECRETS_FILE = os.path.abspath(os.path.join(BASE_DIR, "..", "instance", "database_credentials.json"))

SETTINGS_MODULE = os.environ.get("DJANGO_SETTINGS_MODULE", "")

try:
    with open(SECRETS_FILE) as f:
        DB_PARAMETERS = json.load(f)
except FileNotFoundError:
    DB_PARAMETERS = dict()


def get_database_parameter(key):
    """
    Tenta ler parâmetros nessa ordem:
    1. Parâmetros pela linha de comando
    2. Arquivo JSON em SECRETS_FILE
    :param key: nome do parâmetro a ser recuperado, seja por linha de comando ou do arquivo database_credentials.json
    """

    # se estiver usando o arquivo de settings test ou dev, que usam banco de dados local sqlite, não precisa coletar
    # os parâmetros nem da linha de comando, nem do arquivo de configuração
    if "test" in SETTINGS_MODULE.lower() or "dev" in SETTINGS_MODULE.lower():
        return None

    # parâmetro pela CLI
    value = os.getenv(key)
    if value is not None:
        return value

    # arquivo JSON
    if key in DB_PARAMETERS:
        return DB_PARAMETERS[key]

    raise ImproperlyConfigured(f"Não foi encontrado o atributo '{key}' no CLI nem no arquivo {SECRETS_FILE}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

FORCE_SCRIPT_NAME = "/ngo-ccsh-backend"

ALLOWED_HOSTS = ["proplan.ufsm.br", "localhost", "127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    "ngo_ccsh",  # aplicação própria
    "autenticacao",  # aplicação própria
    "entidades",  # aplicação própria
    "usuarios",  # aplicação própria
    "despesas",  # aplicação própria
    "drf_spectacular",  # para gerar documentação da API
    "django_extensions",  # para gerar diagramas do banco de dados
    "django_filters",  # para filtros em APIs
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ngo_ccsh.urls"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "ngo_ccsh.utils.custom_exception_handler",
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.PaginationWithSize",
    "DEFAULT_RENDERER_CLASSES": ["utils.renders.CustomJSONRenderer"],
    "PAGE_SIZE": 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": os.getenv("JWT_SIGNING_KEY"),
}

CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
    # "TEMPLATES",
]

WSGI_APPLICATION = "ngo_ccsh.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "NAME": "BEE",
        "ENGINE": "ibm_db_django",
        "DATABASE": get_database_parameter("DB_DATABASE"),
        "HOST": get_database_parameter("DB_HOST"),
        "PORT": get_database_parameter("DB_PORT"),
        "USER": get_database_parameter("DB_USERNAME"),
        "PASSWORD": get_database_parameter("DB_PASSWORD"),
        "OPTIONS": {
            "dsn": f"DATABASE={get_database_parameter('DB_DATABASE')};"
                   f"HOSTNAME={get_database_parameter('DB_HOST')};"
                   f"PORT={get_database_parameter('DB_PORT')};"
                   f"PROTOCOL=TCPIP;"
                   f"CURRENTSCHEMA={get_database_parameter('DB_SCHEMA')};"
        },
        "PCONNECT": True,
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "usuarios.Usuario"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# documentação da API
SPECTACULAR_SETTINGS = {
    "TITLE": "ngo-ccsh-backend",
    "DESCRIPTION": "API backend do Controle Orçamentário do CCSH",
    "VERSION": "0.1",
    "SERVE_INCLUDE_SCHEMA": False,
    "GET_LIB_DOC_EXCLUDES": "drf_spectacular.plumbing.get_lib_doc_excludes",
    # OTHER SETTINGS
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

USE_I18N = True
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"

USE_TZ = False  # precisa ser falso para usar ibm db2

STATIC_URL = "/ngo-ccsh-backend/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

APP_FULL_NAME = os.getenv("APP_FULL_NAME") or "Portal Transparência CCSH"
APP_SHORT_NAME = os.getenv("APP_SHORT_NAME")

FRONTEND_URL = os.getenv("FRONTEND_URL")
